# [START gae_python37_cloudsql_config]
runtime: python37

instance_class : femeow

env_variables:
  CLOUD_SQL_USERNAME: root
  CLOUD_SQL_PASSWORD: '123'
  CLOUD_SQL_DATABASE_NAME: femeow
  CLOUD_SQL_CONNECTION_NAME: 'qwiklabs-gcp-02-ae7493d50ef2:asia-southeast2:femeow'
# [END gae_python37_cloudsql_config]
